version: '3.8'

services:
  backend:
    container_name: backend
    image: semenovfilipp/parseq-back:dev # Образ из Docker Hub
    ports:
      - "10300:10300"
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: semenovfilipp/parseq-front:dev # Образ из Docker Hub
    ports:
      - "10100:10100"
    environment:
      - REACT_APP_API_URL=http://localhost:10300
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend